return {
    potionLimitEnabled = true,
    statLimitEnabled = true,
    trainingLimitEnabled = true,
    trainingBankingEnabled = false,
    hudCounterMode = "full",
    hudPosition = "bottomRight",

    attributeCap = 300,
    skillCap = 150,
    potionLimit = 3,
    trainingLimit = 5,
    potionCooldown = 20,
    potionTrackingMode = "counter",
    potionSlotCount = 4,
    maxSlotDisplay = 11,

    excludeSunsDusk = true,

    potions = {
        "T_Var_Sulphur_Weapon",
        "T_Var_Sulphur_Armor",
        "T_Imp_Rune_Sidri",
        "T_Imp_Rune_Sidri2"
    },

    attributes = {
        strength = {},
        intelligence = {},
        willpower = {},
        agility = {},
        speed = {},
        endurance = {},
        personality = {},
        luck = {},
    },

    skills = {
        alchemy = {},
        longblade = {},
        acrobatics = {
            "sc_icarianflight_en",
        },
        bluntweapon = {},
        enchant = {},
        security = {},
        axe = {},
        conjuration = {},
        sneak = {},
        armorer = {},
        alteration = {},
        lightarmor = {},
        mediumarmor = {},
        destruction = {},
        marksman = {},
        heavyarmor = {},
        mysticism = {},
        shortblade = {},
        spear = {},
        restoration = {},
        handtohand = {},
        block = {},
        illusion = {},
        mercantile = {},
        athletics = {},
        unarmored = {},
        speechcraft = {},
    },
}
